### ISSUE TITLE
MeshGraphormer error

### ISSUE THREAD

**Issue by toyxyz** [Fannovel16/comfyui_controlnet_aux#171] opened 2023-12-31 07:46 UTC
When I tried the MeshGraphormer node, I got the following error.

The input image resolution is 512x512. 

Error occurred when executing MeshGraphormer-DepthMapPreprocessor:

__init__(): incompatible constructor arguments. The following argument types are supported:
1. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.uint8])
2. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.uint16])
3. mediapipe.python._framework_bindings.image.Image(image_format: mediapipe::ImageFormat_Format, data: numpy.ndarray[numpy.float32])

Invoked with: kwargs: image_format=, data=array([[[157, 201, 218],
[131, 195, 214],
[131, 191, 215],
...,
[114, 181, 220],
[112, 180, 217],
[119, 178, 215]],

[[165, 216, 225],
[142, 204, 221],
[130, 194, 222],
...,
[115, 181, 221],
[116, 182, 219],
[111, 180, 223]],

[[198, 222, 226],
[163, 215, 221],
[133, 196, 223],
...,
[117, 182, 222],
[116, 182, 221],
[117, 183, 221]],

...,

[[245, 234, 214],
[244, 234, 215],
[244, 234, 213],
...,
[224, 212, 185],
[225, 211, 186],
[224, 211, 186]],

[[244, 232, 214],
[244, 233, 214],
[244, 234, 215],
...,
[224, 212, 186],
[225, 213, 187],
[225, 210, 188]],

[[246, 234, 215],
[244, 233, 213],
[244, 233, 212],
...,
[223, 211, 186],
[225, 212, 186],
[220, 209, 188]]], dtype=uint8)

File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\mesh_graphormer.py", line 61, in execute
depth_map, mask, info = model(np_image, output_type="np", detect_resolution=resolution, mask_bbox_padding=mask_bbox_padding)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\__init__.py", line 29, in __call__
depth_map, mask, info = self.pipeline.get_depth(input_image, mask_bbox_padding)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\pipeline.py", line 300, in get_depth
image = mp.Image(image_format=mp.ImageFormat.SRGB, data=np_image)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Fannovel16** [comment] 2023-12-31 11:01
@toyxyz Does the bug still there after pulling the latest commit?

**Comment by toyxyz** [comment] 2023-12-31 11:53
> @toyxyz Does the bug still there after pulling the latest commit? I can't reproduce it on both Colab and my local machine

After the update, this error occurs. 





2023-12-31 20:52:43,436 - custom_mesh_graphormer.modeling.hrnet.hrnet_cls_net_gridfeat - INFO - => init weights from normal distribution
2023-12-31 20:52:44,123 - custom_mesh_graphormer.modeling.hrnet.hrnet_cls_net_gridfeat - INFO - => loading pretrained model C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
=> loading pretrained model C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
2023-12-31 20:52:45,289 - root - ERROR - !!! Exception during processing !!!
2023-12-31 20:52:45,291 - root - ERROR - Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\mesh_graphormer.py", line 61, in execute
    depth_map, mask, info = model(np_image, output_type="np", detect_resolution=resolution, mask_bbox_padding=mask_bbox_padding)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\__init__.py", line 29, in __call__
    depth_map, mask, info = self.pipeline.get_depth(input_image, mask_bbox_padding)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\pipeline.py", line 377, in get_depth
    cropped_depthmap, pred_2d_keypoints = self.run_inference(graphormer_input.astype(np.uint8), self._model, self.mano_model, self.mesh_sampler, scale, int(crop_len))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\pipeline.py", line 249, in run_inference
    pred_camera, pred_3d_joints, pred_vertices_sub, pred_vertices, hidden_states, att = Graphormer_model(batch_imgs, mano, mesh_sampler)
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mesh_graphormer\modeling\bert\e2e_hand_network.py", line 37, in forward
    template_vertices_sub = mesh_sampler.downsample(template_vertices)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mesh_graphormer\modeling\_mano.py", line 160, in downsample
    y = spmm(self._D[j], y)
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mesh_graphormer\modeling\_mano.py", line 83, in spmm
    return SparseMM.apply(sparse, dense)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mesh_graphormer\modeling\_mano.py", line 72, in forward
    return torch.matmul(sparse, dense)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_SparseCUDA__mm)

Prompt executed in 4.37 seconds

**Comment by nomadoor** [comment] 2023-12-31 12:07
I got the same error too.
I asked ChatGPT and made the following modification and it worked correctly.
This might be helpful for you.

`path\to\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_mesh_graphormer\modeling\_mano.py`

```before.py
def spmm(sparse, dense):
    return SparseMM.apply(sparse, dense)
```

```after.py
def spmm(sparse, dense):
    device = torch.device('cuda:0')
    sparse = sparse.to(device)
    dense = dense.to(device)
    return SparseMM.apply(sparse, dense)
```

**Comment by toyxyz** [comment] 2023-12-31 12:22
After modifying the code as suggested by nomadoor, the above error disappeared. However, I get this error when the input image does not have hands. 


2023-12-31 21:20:32,548 - root - ERROR - !!! Exception during processing !!!
2023-12-31 21:20:32,549 - root - ERROR - Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\mesh_graphormer.py", line 61, in execute
    depth_map, mask, info = model(np_image, output_type="np", detect_resolution=resolution, mask_bbox_padding=mask_bbox_padding)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mesh_graphormer\__init__.py", line 35, in __call__
    depth_map, mask = HWC3(depth_map), HWC3(mask)
                                       ^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 32, in HWC3
    assert x.dtype == np.uint8
           ^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by Fannovel16** [comment] 2023-12-31 12:50
@nomadoor @toyxyz Pushed the fix

**Comment by toyxyz** [comment] 2023-12-31 13:01
Now there is no error if there are no hands in the image! 

However, the hand depth image looks like it's flipped. 

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/02d15eaa-a134-4dd3-921a-21f131ec1a19)

**Comment by nomadoor** [comment] 2023-12-31 13:06
I thought it was just my imagination, but I'm having the same problem.

**Comment by Fannovel16** [comment] 2023-12-31 13:08
@toyxyz Can you send the input image? I gonna test to see if this issue exists on the original implementation

**Comment by toyxyz** [comment] 2023-12-31 13:10
> @toyxyz Can you send the input image? I gonna test to see if this issue exists on the original implementation

Here! 

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/1fe40dd7-8b15-4487-a74c-ef67d67c42a7)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/377924c7-3fae-419c-a9cf-612b701c13f1)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/2a28defb-b449-4388-b3a9-3522553a4392)

**Comment by Fannovel16** [comment] 2023-12-31 13:33
@toyxyz Result from original repo. Indeed there is something wrong in my implementation
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/95d81bea-615a-48bc-911e-2fcc09273fa1)

**Comment by Fannovel16** [comment] 2024-01-01 04:13
@toyxyz @nomadoor I pushed the fix but it comes with a trade-off: Only works on NVidia or AMD cards

**Comment by toyxyz** [comment] 2024-01-01 05:10
> @toyxyz @nomadoor I pushed the fix but it comes with a trade-off: Only works on NVidia or AMD cards. Can you confirm if it works on your machine? [68fdfa0](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/68fdfa02ba3f7ce98a0a4e32c55b002f84243926)

Thanks! I've updated and tried again, but I'm still having problems. 

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/23828cb8-443a-4e50-b74d-aaa6fedc1e39)

**Comment by Fannovel16** [comment] 2024-01-01 07:11
@toyxyz Weird. I don't have that problem. I doubt that `git pull` command doesn't work because you changed the code. Try manually delete the repo then reclone it

**Comment by toyxyz** [comment] 2024-01-01 07:44
I deleted the folder and git cloned repo manually, but I still have the same problem. 

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/4e41a629-6b01-4754-8e9b-81729bb1a02c)

**Comment by Fannovel16** [comment] 2024-01-01 08:07
@toyxyz What is the version of `transformers` in your env?

**Comment by Fannovel16** [comment] 2024-01-01 08:24
@toyxyz Oh finally I found out where is the bug. The cause is mediapipe

**Comment by Fannovel16** [comment] 2024-01-01 08:33
After some testing, I found out that the bug occurs when mediapipe is at version 0.10.5+

**Comment by Fannovel16** [comment] 2024-01-01 08:58
@toyxyz I pushed the fix which works on both new and old mediapipe version
mediapipe v0.10.9 (latest)
![mp_latest_result](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/239c0e21-fbd9-488f-8ff0-2f0cd790f50f)
mediapipe v0.10.0
![mp_0 10 0_result](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/f3426b1e-4b26-4763-adc0-49efbbf38c0a)

**Closed** 2024-01-01 09:12 UTC

**Comment by toyxyz** [comment] 2024-01-01 10:03
Now it's working perfect, thank you!

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8006000/133847b6-077a-4381-b201-0cb43417a226)

**Comment by nomadoor** [comment] 2024-01-01 11:55
Thank you for your great work👏

**Comment by sd827999094** [comment] 2024-01-08 06:43
can show the workflow ?
