### ISSUE TITLE
DWPose might run very slowly

### ISSUE THREAD

**Issue by ekka007** [Fannovel16/comfyui_controlnet_aux#110] opened 2023-11-14 17:30 UTC
UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

**Comment by DmytroSokhach** [comment] 2023-11-17 00:09
I think it is duplicate of  "Onnxruntime not found or doesn't come with acceleration providers" #75

**Comment by Fannovel16** [comment] 2023-11-17 06:22
@ekka007 Close this to avoid duplication. You can post your issue at https://github.com/Fannovel16/comfyui_controlnet_aux/issues/75

**Closed by Fannovel16** 2023-11-17 06:22 UTC
